name: Typecheck, lint, format and test

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

jobs:
    lint-typecheck:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Typecheck
              run: npm run check:types

            - name: Lint
              run: npm run check:lint

            - name: Format
              run: npm run check:format

            - name: Test
              run: npm run check:test
