name: EAS Build A Release Candidate
on:
    workflow_dispatch:
    push:
        tags:
            - 'rc/*'
jobs:
    build:
        name: Install & build release candidate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18.x
                  cache: npm
            - name: Setup Expo & EAS
              uses: expo/expo-github-action@v8
              with:
                  eas-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}
            - name: Install dependencies
              run: npm ci
            - name: Build on EAS
              run: eas build --platform all --non-interactive --no-wait --profile preview
